import React, { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import Notice from "@/components/Notice";
import { adminGames, adminLogin, adminPost, errText } from "@/lib/api";

const KEY = "lb_admin_pw";
export default function GamesAdmin() {
  const [pw, setPw] = useState(() => localStorage.getItem(KEY) || "");
  const [authed, setAuthed] = useState(false); const [data, setData] = useState(null);
  const [error, setError] = useState(""); const [note, setNote] = useState("");
  const [model, setModel] = useState({ id: "nebius-main", provider: "nebius", label: "Nebius main",
    model: "meta-llama/Llama-3.3-70B-Instruct", base_url: "https://api.tokenfactory.nebius.com/v1", credential_env: "NEBIUS_API_KEY", enabled: true });
  const refresh = useCallback(async (password = pw) => { try { setData(await adminGames(password)); setAuthed(true); setError(""); } catch (e) { setError(errText(e)); if (e?.response?.status === 401) setAuthed(false); } }, [pw]);
  useEffect(() => { if (pw) refresh(pw); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (!authed) return; const id = setInterval(() => refresh(), 8000); return () => clearInterval(id); }, [authed, refresh]);
  const act = async (path, body, message) => { setError(""); setNote(""); try { const out = await adminPost(pw, path, body); setNote(message || "Done."); await refresh(); return out; } catch (e) { setError(errText(e)); } };
  const login = async (e) => { e.preventDefault(); try { await adminLogin(pw); localStorage.setItem(KEY, pw); await refresh(pw); } catch (x) { setError(errText(x)); } };
  if (!authed) return <><Notice /><main className="page"><h1 className="page__title">Games desk</h1><form className="sheet" onSubmit={login}><label className="field"><span className="field__label">Keeper password</span><input type="password" value={pw} onChange={(e) => setPw(e.target.value)} /></label>{error ? <p className="sheet__error">{error}</p> : null}<button className="btn">Unlock</button></form></main></>;
  return <><Notice /><main className="page page--wide admin games-admin"><header className="games-admin__head"><div><p className="arena-kicker">Keeper controls</p><h1 className="page__title">The games desk</h1></div><Link to="/admin">Direct wall admin</Link></header>
    {note ? <p className="admin__pre">{note}</p> : null}{error ? <p className="sheet__error">{error}</p> : null}
    <h2>Sponsored campaigns</h2><table><thead><tr><th>Product</th><th>Sponsor / schedule</th><th>Money</th><th>Status</th><th>Do</th></tr></thead><tbody>{(data?.campaigns || []).map((c) => <tr key={c.id}><td><strong>{c.product_name}</strong><br /><a href={c.product_url} target="_blank" rel="noreferrer">verify destination</a></td><td>{c.company_name}<br />{new Date(c.event_at).toLocaleString()}<br /><small>{c.sponsor_email}</small></td><td>₹{(c.platform_fee_paise / 100).toLocaleString()} fee<br />₹{(c.prize_paise / 100).toLocaleString()} prize</td><td><span className="tag">{c.status}</span></td><td>{c.status === "pending_review" ? <><button className="btn btn--sm" onClick={() => act(`/admin/games/campaigns/${c.id}/approve`, {}, "Campaign opened.")}>Approve</button> <button className="btn btn--sm btn--ghost" onClick={() => act(`/admin/games/campaigns/${c.id}/reject`, {}, "Campaign rejected.")}>Reject</button></> : c.status !== "rejected" ? <Link to={`/campaign/${c.slug}`}>public page</Link> : "—"}</td></tr>)}</tbody></table>
    <h2>Creative submissions</h2><table><thead><tr><th>Ad</th><th>Creator</th><th>Constraint</th><th>Status</th><th>Do</th></tr></thead><tbody>{(data?.submissions || []).map((s) => <tr key={s.id}><td><strong>{s.creative?.headline}</strong><br /><small>{s.creative?.model?.label}</small></td><td>{s.creator_name}<br /><small>{s.creator_email}</small></td><td>{s.constraint}</td><td><span className="tag">{s.status}</span></td><td>{s.status === "submitted" ? <><button className="btn btn--sm" onClick={() => act(`/admin/games/submissions/${s.id}/approve`, {}, "Ad approved.")}>Approve</button> <button className="btn btn--sm btn--ghost" onClick={() => act(`/admin/games/submissions/${s.id}/reject`, {}, "Ad rejected.")}>Reject</button></> : s.status === "approved" ? <button className="btn btn--sm" onClick={() => act(`/admin/games/submissions/${s.id}/queue`, {}, "Challenger queued.")}>Queue</button> : "—"}</td></tr>)}</tbody></table>
    <h2>Live events</h2><table><thead><tr><th>Event</th><th>Queue</th><th>Status</th><th>Do</th></tr></thead><tbody>{(data?.events || []).map((e) => <tr key={e.id}><td><Link to={`/event/${e.slug}`}>{e.slug}</Link></td><td>{e.queue?.length || 0} ads</td><td><span className="tag tag--live">{e.status}</span></td><td>{!e.current_round_id ? <button className="btn btn--sm" onClick={() => act(`/admin/games/events/${e.id}/start`, {}, "Event started.")}>Start show</button> : e.status === "live" ? <button className="btn btn--sm" onClick={() => act(`/admin/games/events/${e.id}/advance`, {}, "Round advanced.")}>Force next round</button> : "Final"}</td></tr>)}</tbody></table>
    <h2>Model catalog</h2><form className="admin__row" onSubmit={(e) => { e.preventDefault(); act("/admin/games/models", model, "Model saved."); }}>
      {Object.keys(model).filter((k) => k !== "enabled").map((k) => <input key={k} placeholder={k} value={model[k]} onChange={(e) => setModel({ ...model, [k]: e.target.value })} />)}<button className="btn btn--sm">Save provider</button></form>
    <table><thead><tr><th>Label</th><th>Provider/model</th><th>Endpoint</th><th>Secret reference</th></tr></thead><tbody>{(data?.models || []).map((m) => <tr key={m.id}><td>{m.label}</td><td>{m.provider}<br />{m.model}</td><td>{m.base_url}</td><td>{m.credential_env}</td></tr>)}</tbody></table>
    <h2>Prize payouts</h2><table><thead><tr><th>Campaign</th><th>Winner</th><th>Amount</th><th>Status</th><th>Do</th></tr></thead><tbody>{(data?.payouts || []).map((p) => <tr key={p.campaign_id}><td>{p.campaign_id}</td><td>{p.winner_id || "not decided"}</td><td>₹{((p.amount_paise || 0) / 100).toLocaleString()}</td><td>{p.status}</td><td>{["claimed", "paid", "failed"].map((s) => <button key={s} className="btn btn--sm btn--ghost" onClick={() => act(`/admin/games/payouts/${p.campaign_id}/${s}`, {}, `Payout marked ${s}.`)}>{s}</button>)}</td></tr>)}</tbody></table>
  </main></>;
}
